server:
    port: 80

#EurekaClient配置
eureka:
    client:
        register-with-eureka: false #不像eureka中注册自己
        service-url:
            defaultZone: http://eureka7071.com:7071/eureka/,http://eureka7072.com:7072/eureka/,http://eureka7073.com:7073/eureka/