server:
    port: 7979
spring:
    application:
        name: gateway-7979
    #Gateway配置
    cloud:
        gateway:
            routes:
            - id: provider-user-8070      # 指定路由唯一标识
              # uri: http://localhost:8070/ # 指定路由服务的地址
              uri: lb://PROVIDER-USER # lb代表转发后台服务使用负载均衡，users表示服务注册中心上的服务名
              predicates:
              # 指定路由规则，及访问当前端口localhost:7979/dept/get/的时候会转发到localhost:8070/userprovider/user/get/下所有路径
              - Path=/userprovider/user/getbyid/**
            
            - id: provider-user-8071      # 指定路由唯一标识
             # uri: http://localhost:8071/ # 指定路由服务的地址
              uri: lb://PROVIDER-USER # lb代表转发后台服务使用负载均衡，users表示服务注册中心上的服务名
              predicates:
              # 指定路由规则，及访问当前端口localhost:7979/userprovider/user/userlist的时候会转发到localhost:8071/userprovider/user/userlist
              - Path=/userprovider/user/userlist
              # - After=2022-04-04T19:00:00.124+8:00[Asia/Shanghai] #After断言，必要到指定时间之后执行才能生效
              # - Before=2022-04-04T19:00:00.124+8:00[Asia/Shanghai]  #Before断言，在指定时间之前才会生效，过了不生效
              # - Between=2022-04-04T19:00:00.124+8:00[Asia/Shanghai],2022-04-05T19:00:00.124+8:00[Asia/Shanghai] #指定时间范围内生效
              # - Cookie=username,luo #必须携带指定Cookie username = luo的用户才能访问
              # - Cookie=username,[A-Za-z0-9]+ #必须携带指定Cookie username = 任意大小写字母和数字
              # - Header=X-Request-Id, \d+ #必须含有指定的请求头
              # - Method=GET # 指定请求方法
              
              filters:
              # 路由filter,经过上面路由对象的所有转发请求，都会添加
              - AddRequestHeader=User-Name, luo #添加指定请求头User-Name 值为luo
              - AddRequestParameter=color, blue #添加指定的请求参数
              - AddResponseHeader=X-Response-Red, AA #添加指定的响应加入头信息
              - PrefixPath=/temp #给路由对象所有转发的url加入指定的前缀信息
              - StripPrefix=2 #给路由对象所有转发请求的url取消指定的2（N）个前缀
              
eureka:
    client:
        service-url:
            defaultZone: http://eureka7071.com:7071/eureka/,http://eureka7072.com:7072/eureka/,http://eureka7073.com:7073/eureka/
    instance:
        instance-id: Gateway7979.com
        prefer-ip-address: true
        
#通过网关提供web路径查看路由详细规则 http://localhost:7979/actuator/gateway/routes
management:
    endpoints:
        web:
            exposure:
                include: "*"