server:
    port: 9527
#微服务名称
spring:
    application:
        name: springcloud-zuul-9527
#集群
eureka:
    client:
        service-url:
            defaultZone: http://eureka7071.com:7071/eureka/,http://eureka7072.com:7072/eureka/,http://eureka7073.com:7073/eureka/
    instance:
        instance-id: zuul9527.com
        prefer-ip-address: true #显示ip
info:
    app.name: zuul-9572
    company.name: com.xison
    
#zuul路由配置
zuul:
    routes:
        myuser.serverId: provider-user # eureka注册中心的服务提供方路由名称
        # 将eureka注册中心的服务提供方路由名称 改为自定义路由名称。
        myuser.path: /myuser/** # http://www.myzuul.com:9527/provider-user/userprovider/user/userlist和http://www.myzuul.com:9527/myuser/userlist两个都能访问
        #ignored-services: provider-user #不能在使用http://www.myzuul.com:9527/provider-user/这个路径访问
        #ignored-services: "*"
        prefix: /userprovider/user # 设置公共的前缀